version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 9100:9000
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9300:80